name: build
on:
  merge_group: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        run: cat $GITHUB_EVENT_PATH
